name: Update version and Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.email "forth.developer@gmail.com"
          git config --global user.name "Forthtilliath"

      - name: Update version
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ $COMMIT_MSG =~ ^fix: ]]; then
            npm version patch
          elif [[ $COMMIT_MSG =~ ^!f: ]]; then
            npm version major
          else
            npm version minor
          fi

      - name: Push changes
        run: |
          git push --follow-tags

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: "@forthtilliath"

      - name: Install dependencies
        run: npm ci

      - name: Bump version and create a release
        id: create_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set up npm authentication
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
